### ISSUE TITLE
News_agent example doesn't work

### ISSUE THREAD

**Issue by Agent009** [swarmzero/examples#1]
Hi,

The `news_agent` example doesn't work.
If you use the `FastAPI` Swagger UI to send the request to the `chat` API, it complains about the file field being empty, or the chat data being malformed.

![image](https://github.com/user-attachments/assets/593ade2b-248e-4efd-bf30-6a80aef63532)

If you send a JSON request, it complains about missing fields.

![image](https://github.com/user-attachments/assets/f34d15a4-530a-49e0-959f-6fed33866e99)

You can't win either way, and this is with the base code without any modifications.

**Comment by ToJen** [comment]
Hello @Agent009, the Swagger UI has issues with files sometimes. You would have to try (de)selecting the `files`. Also, if you call it directly e.g. via curl or Postman, you need to send it as `multipart/form-data`. We are in the process of changing this. Currently, you're sending it as a JSON object which won't work.

**Comment by ToJen** [comment]
Hello @Agent009, there's now a newer example of an agent that is a much better at searching the web -> #3
